api:
  line_id: 8000
  base_url: "https://api.olhovivo.sptrans.com.br/v2.1"
  endpoints:
    - "/Login/Autenticar"
    - "/Linha"
    - "/Parada/BuscarParadasPorLinha"
    - "/Posicao"
    - "/Corredor"
    - "/Previsao"
    - "/KMZ"

paths:
  data:
    - 'data/raw'