paths:
  raw_data: 'data\raw'
  
files:
  agency: "agency.txt"
  routes: "routes.txt"
  trips: "trips.txt"
  stop_time: "stop_times.txt"
  calendar: "calendar.txt"
  frequencies: "frequencies.txt"
  stops: "stop_times.txt"

parameters:
  timezone: "America/Sao_Paulo"